### ISSUE TITLE
cublas_v2.h not found in OS X

### ISSUE THREAD

**Issue by alexscheelmeyer** [melisgl/mgl-mat#1]
Hi

I am trying to use this library on a mac, hopefully OS X is a supported platform?

In any case when I try to load it I get an error saying cublas_v2.h cannot be found :

```
* (ql:quickload :mgl-mat)
To load "mgl-mat":
  Load 1 ASDF system:
    mgl-mat
; Loading "mgl-mat"
..........; cc -m64 -I /opt/local/include/ -I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/ -o /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c

debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {1002C0E863}>: External process exited with code 1.
Command was: "cc" "-m64" "-I" "/opt/local/include/" "-I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/" "-o" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c"
Output was:
/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c:6:10: fatal error: 'cublas_v2.h' file not found
#include <cublas_v2.h>
         ^
1 error generated.
```

I can load cl-cuda ok and I have Cuda Toolkit V7.0 installed.

It seems like the issue is that it assumes an include-path of "/opt/local/include/". For me the cublas_v2.h file is located at "/Developer/NVIDIA/CUDA-7.0/include/" which is symlinked at "/usr/local/cuda/include".

Thanks.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> Hi
> 
> I am trying to use this library on a mac, hopefully OS X is a
> supported platform?

Hello. Yes, although I have no access to OS X ...

Looking at what CL-CUDA does in type-grovel.lisp:

```
#+darwin (include "cuda/cuda.h")
#-darwin (include "cuda.h")
```

I think your setup must be standard so I added the same logic to
MGL-MAT's cublas-grovel.lisp. Please pull the latest version and retry.

**Comment by alexscheelmeyer** [comment]
That might be part of the solution, but I am still getting the same error (only now it is cuda/cublas_v2.h that is not found).

```
* (ql:quickload :mgl-mat)
To load "mgl-mat":
  Load 1 ASDF system:
    mgl-mat
; Loading "mgl-mat"
..........; cc -m64 -I /opt/local/include/ -I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/ -o /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c

debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {1002C0E943}>: External process exited with code 1.
Command was: "cc" "-m64" "-I" "/opt/local/include/" "-I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/" "-o" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c"
Output was:
/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c:6:10: fatal error: 'cuda/cublas_v2.h' file not found
#include <cuda/cublas_v2.h>
         ^
1 error generated.
```

I am not sure what else is different to what cl-cuda does.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> That might be part of the solution, but I am still getting the same error (only now it is cuda/cublas_v2.h that is not found).
> 
> ```
> * (ql:quickload :mgl-mat)
> To load "mgl-mat":
>   Load 1 ASDF system:
>     mgl-mat
> ; Loading "mgl-mat"
> ..........; cc -m64 -I /opt/local/include/ -I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/ -o /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c
> 
> debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {1002C0E943}>: External process exited with code 1.
> Command was: "cc" "-m64" "-I" "/opt/local/include/" "-I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/" "-o" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c"
> Output was:
> /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c:6:10: fatal error: 'cuda/cublas_v2.h' file not found
> #include <cuda/cublas_v2.h>
>          ^
> 1 error generated.
> ```
> 
> I am not sure what else is different to what cl-cuda does.

Is cublas_v2.h available at /usr/local/include/cuda/cublas_v2.h?

**Comment by alexscheelmeyer** [comment]
No, it is available at /usr/local/cuda/include/cublas_v2.h - but you were close :)

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> No, it is available at /usr/local/cuda/include/cublas_v2.h - but you were close :)

Since you compiled cl-cuda succesfully, /usr/local/include/cuda/cuda.h
must be there. It's strange to have cublas_v2.h in another directory.
Perhaps _my_ setup is unusual (I'm using debian packages).

What does

```
ls -lAR /usr/local/include/cuda/
```

say?

**Comment by alexscheelmeyer** [comment]
ls: /usr/local/include/cuda/: No such file or directory

the way it seems to be setup is that /usr/local/cuda/ is a folder of symlinks to the newest installed version of the cuda toolkit.

```
ls -l /usr/local/cuda
total 88
lrwxr-xr-x   1 root  wheel    57 Mar 21 17:25 CUDA_Toolkit_Release_Notes.txt -> /Developer/NVIDIA/CUDA-7.0/CUDA_Toolkit_Release_Notes.txt
lrwxr-xr-x   1 root  wheel    35 Mar 21 17:25 EULA.txt -> /Developer/NVIDIA/CUDA-7.0/EULA.txt
lrwxr-xr-x   1 root  wheel    30 Mar 21 17:25 bin -> /Developer/NVIDIA/CUDA-7.0/bin
lrwxr-xr-x   1 root  wheel    30 Mar 21 17:25 doc -> /Developer/NVIDIA/CUDA-7.0/doc
lrwxr-xr-x   1 root  wheel    33 Mar 21 17:25 extras -> /Developer/NVIDIA/CUDA-7.0/extras
lrwxr-xr-x   1 root  wheel    34 Mar 21 17:25 include -> /Developer/NVIDIA/CUDA-7.0/include
drwxr-xr-x  46 root  wheel  1564 Mar 21 17:25 lib
lrwxr-xr-x   1 root  wheel    36 Mar 21 17:25 libnsight -> /Developer/NVIDIA/CUDA-7.0/libnsight
lrwxr-xr-x   1 root  wheel    34 Mar 21 17:25 libnvvp -> /Developer/NVIDIA/CUDA-7.0/libnvvp
lrwxr-xr-x   1 root  wheel    31 Mar 21 17:25 nvvm -> /Developer/NVIDIA/CUDA-7.0/nvvm
lrwxr-xr-x   1 root  wheel    30 Mar 21 17:25 src -> /Developer/NVIDIA/CUDA-7.0/src
lrwxr-xr-x   1 root  wheel    32 Mar 21 17:25 tools -> /Developer/NVIDIA/CUDA-7.0/tools
```

The include folder contains both cuda.h and cublas_v2.h

**Comment by alexscheelmeyer** [comment]
btw:

```
* cl-cuda:*sdk-not-found*

NIL
```

so cl-cuda does seem to find the sdk.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> ls: /usr/local/include/cuda/: No such file or directory
> 
> the way it seems to be setup is that /usr/local/cuda/ is a folder of
> symlinks to the newest installed version of the cuda toolkit.
> 
> ```
> ls -l /usr/local/cuda
> total 88
> lrwxr-xr-x 1 root wheel 57 Mar 21 17:25 CUDA_Toolkit_Release_Notes.txt
> -> /Developer/NVIDIA/CUDA-7.0/CUDA_Toolkit_Release_Notes.txt
> lrwxr-xr-x   1 root  wheel    35 Mar 21 17:25 EULA.txt -> /Developer/NVIDIA/CUDA-7.0/EULA.txt
> lrwxr-xr-x   1 root  wheel    30 Mar 21 17:25 bin -> /Developer/NVIDIA/CUDA-7.0/bin
> lrwxr-xr-x   1 root  wheel    30 Mar 21 17:25 doc -> /Developer/NVIDIA/CUDA-7.0/doc
> lrwxr-xr-x   1 root  wheel    33 Mar 21 17:25 extras -> /Developer/NVIDIA/CUDA-7.0/extras
> lrwxr-xr-x   1 root  wheel    34 Mar 21 17:25 include -> /Developer/NVIDIA/CUDA-7.0/include
> drwxr-xr-x  46 root  wheel  1564 Mar 21 17:25 lib
> lrwxr-xr-x   1 root  wheel    36 Mar 21 17:25 libnsight -> /Developer/NVIDIA/CUDA-7.0/libnsight
> lrwxr-xr-x   1 root  wheel    34 Mar 21 17:25 libnvvp -> /Developer/NVIDIA/CUDA-7.0/libnvvp
> lrwxr-xr-x   1 root  wheel    31 Mar 21 17:25 nvvm -> /Developer/NVIDIA/CUDA-7.0/nvvm
> lrwxr-xr-x   1 root  wheel    30 Mar 21 17:25 src -> /Developer/NVIDIA/CUDA-7.0/src
> lrwxr-xr-x   1 root  wheel    32 Mar 21 17:25 tools -> /Developer/NVIDIA/CUDA-7.0/tools
> ```
> 
> The include folder contains both cuda.h and cublas_v2.h

Hmm, maybe cl-cuda is not finding the sdk either. Does
CL-CUDA.DRIVER-API:_SDK-NOT-FOUND_ evaluate to NIL?

**Comment by alexscheelmeyer** [comment]
> Does CL-CUDA.DRIVER-API:*SDK-NOT-FOUND* evaluate to NIL?

Yes.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> > Does CL-CUDA.DRIVER-API:*SDK-NOT-FOUND* evaluate to NIL?
> 
> Yes.

While I'm not finding what the difference is, can you do another quick
experiment? Please, blow away the compilation cache, on my system it
goes like this:

  rm -rf /home/mega/.cache/common-lisp/sbcl-1.2.9.77-3f2c04a-linux-x64/home/mega/quicklisp/local-projects/cl-cuda/

Restart the lisp and load cl-cuda. Please show the line with the
invocation of cc.

**Comment by alexscheelmeyer** [comment]
This is the line

```
[package cl-cuda.driver-api].; cc -m64 -I /opt/local/include/ -I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/ -o /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/cl-cuda/src/driver-api/type-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/cl-cuda/src/driver-api/type-grovel.c
; /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/cl-cuda/src/driver-api/type-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/cl-cuda/src/driver-api/type-grovel.grovel-tmp.lisp
```

So it uses the same include path but is not giving any error.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> So it uses the same include path but is not giving any error.

I finally noticed that it's /opt/. ls -l /opt/local/include/?

**Comment by alexscheelmeyer** [comment]
Perhaps related to this other difference, that cl-cuda in library.lisp loads the cuda framework for os x instead of .so file on unix?

``` lisp
(cffi:define-foreign-library libcuda
  (:darwin (:framework "CUDA"))
  (:unix (:or "libcuda.so" "libcuda64.so")))
```

**Comment by alexscheelmeyer** [comment]
"ls -l /opt/local/include/" does give a listing but only "libusb" and no cuda. Also as far as I know it is only used by the homebrew package manager.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> "ls -l /opt/local/include/" does give a listing but only "libusb" and
> no cuda. Also as far as I know it is only used by the homebrew package
> manager.

The question is how to determine the system include path ...

**Comment by melisgl** [comment]
What does this say?

```
gcc -x c -v -E /dev/null
```

**Comment by alexscheelmeyer** [comment]
```
Alex-2:~ alexscheelmeyer$ gcc -x c -v -E /dev/null
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.10.0 -E -disable-free -disable-llvm-verifier -main-file-name null -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 241.9 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0 -fdebug-compilation-dir /Users/alexscheelmeyer -ferror-limit 19 -fmessage-length 112 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fdiagnostics-show-option -fcolor-diagnostics -vectorize-slp -o - -x c /dev/null
clang -cc1 version 6.0 based upon LLVM 3.5svn default target x86_64-apple-darwin14.1.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 170 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```

**Comment by melisgl** [comment]
/usr/local/include/cuda/ doesn't exist, so /usr/local/include/ is out. Which one of the above has cuda/cuda.h (but not cuda/cublas_v2)???

**Comment by alexscheelmeyer** [comment]
Yes, /usr/local/include/cuda/ does not exist but /usr/local/cuda/include/ does (cuda and include switched around). In /usr/local/cuda/include/ both cuda.h and cublas_v2.h exists.

Interestingly cl-cuda loads the cuda framework on OS X (in library.lisp). Frameworks on OS X contains both shared libraries and header files. The cuda framework is installed as /Library/Frameworks/CUDA.framework/ but /Library/Frameworks/CUDA.framework/Headers/ only contain cuda.h, not cublas_v2.h.

**Comment by melisgl** [comment]
alexscheelmeyer notifications@github.com writes:

> Yes, /usr/local/include/cuda/ does not exist but
> /usr/local/cuda/include/ does (cuda and include switched around). In
> /usr/local/cuda/include/ both cuda.h and cublas_v2.h exists.
> 
> Interestingly cl-cuda loads the cuda framework on OS X (in
> library.lisp). Frameworks on OS X contains both shared libraries and
> header files. The cuda framework is installed as
> /Library/Frameworks/CUDA.framework/ but
> /Library/Frameworks/CUDA.framework/Headers/ only contain cuda.h, not
> cublas_v2.h.

I don't claim to understand how the below command ended up looking in
/Library/Frameworks/CUDA.framework/Headers/.

[package cl-cuda.driver-api].; cc -m64 -I /opt/local/include/ -I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/ -o /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/cl-cuda/src/driver-api/type-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/cl-cuda/src/driver-api/type-grovel.c

Anyway, I pushed a new version that includes "cuda/include/cublas_v2.h"
on darwin. We could have done that much earlier, but I wanted to
understand what the right solution is ...

**Comment by melisgl** [comment]
Oh, I see. `(framework directory)` above means that  `*/Headers/` are included.

**Comment by alexscheelmeyer** [comment]
Yes, it seems that the /opt/local/include/ include path is not used for anything in cl-cuda but it still finds cuda.h since it loads the framework.
Changing to include cuda/include/cublas_v2.h actually still does not work, since it is still looking for it based on /opt/local/include/ (from the -I argument) or /usr/local/include (from the gcc settings).

```
..........; cc -m64 -I /opt/local/include/ -I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/ -o /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel /Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c

debugger invoked on a CFFI-GROVEL:GROVEL-ERROR in thread #<THREAD "main thread" RUNNING {1002C0E943}>: External process exited with code 1.
Command was: "cc" "-m64" "-I" "/opt/local/include/" "-I/Users/alexscheelmeyer/quicklisp/dists/quicklisp/software/cffi_0.14.0/" "-o" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel" "/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c"
Output was:
/Users/alexscheelmeyer/.cache/common-lisp/sbcl-1.2.2-macosx-x64/Users/alexscheelmeyer/quicklisp/local-projects/mgl-mat/src/cublas-grovel.c:6:10: fatal error: 'cuda/include/cublas_v2.h' file not found
#include <cuda/include/cublas_v2.h>
         ^
1 error generated.
```

**Comment by melisgl** [comment]
Argh. So the right directory is not reachable from cc's system search path. I'll try to use nvcc to do the groveling.

**Comment by melisgl** [comment]
I added /usr/local/cuda/include/ to the search path. Ran into a cffi grovel issue, too. Fingers crossed.

**Comment by melisgl** [comment]
The cffi grovel issue, just for the record: https://bugs.launchpad.net/cffi/+bug/1434900

**Comment by alexscheelmeyer** [comment]
Great, that did it - it works now!

Thanks!

**Comment by mebrar** [comment]
@melisgl How can you manage to add the above path to search path?

**Comment by deniszh** [comment]
Faced same issue, fixed by install CUDA _toolkit_. CUDA driver is not enough. In case of MacOS - please use [that manual](https://gist.github.com/robertsdionne/f58a5fc6e5d1d5d2f798) (but versions of python and macos should be fixed there)
